### ISSUE TITLE
wish: support .properties extension

### ISSUE THREAD

**Issue by markstos** [tkellen/js-interpret#10]
`node`config` is considering using this module for loading config files. `.properties` is one of the file formats we currently support, but would prefer to support through `interpret`. It's currently parsed by the `properties` module:

https://www.npmjs.com/package/properties

**Comment by phated** [comment]
ref https://github.com/gagle/node-properties/issues/14

I think we close this if no movement is taken before 1.0 release

**Comment by tkellen** [comment]
I'm closing.  @markstos / @gagle please feel free to open a PR to add support for this module if you'd like!
