### ISSUE TITLE
Latest livescript 1.4 package breaks interpret

### ISSUE THREAD

**Issue by ljconde** [tkellen/js-interpret#23]
Latest livescript npm package (1.4) is now 'livescript' instead of 'LiveScript'. Interpret is currently expecting LiveScript (https://github.com/tkellen/js-interpret/blob/master/index.js#L18) and this is causing anything using the newer livescript package to fail.

**Comment by tkellen** [comment]
Do older versions work with "livescript"?

**Comment by ljconde** [comment]
I don't believe it does. 'LiveScript' has 25 releases available, vs only 2 releases in the new 'livescript'. 
https://www.npmjs.com/package/LiveScript
https://www.npmjs.com/package/livescript

**Comment by tkellen** [comment]
resolved in 6131267d406f0b2b805ba71363daa2e9aa21e839.  liftoff needs to updated to support this, however.
