### ISSUE TITLE
babel-core

### ISSUE THREAD

**Issue by thejameskyle** [tkellen/js-interpret#29]
It'd be nice if you could conditionally load `babel-core` instead of `babel` when it exists.

`babel-core` is the lightweight version of babel that plugins like `babelify` use.

This should work just as well:

```js
require('babel-core/register')
```

Ref: https://github.com/gulpjs/gulp/issues/1127

**Comment by phated** [comment]
@thejameskyle I'm pretty swamped the next couple of weeks.  Could you submit a PR that adds it as the first option to `.babel.js` extension?  An example of supporting multiple loaders is the `.jsx` extension https://github.com/tkellen/js-interpret/blob/master/index.js#L24 (I'm guessing `babel-core` should be added to that list also)

**Comment by bucaran** [comment]
@thejameskyle If I have a project that uses `babel-runtime` (for generator support, etc.) but also installs the `require` hook, is it still recommended to add `babel-core` as a runtime dependency of my project?

**Comment by thejameskyle** [comment]
The `babel` package uses `babel-core` internally, if you don't need the CLI I suggest replacing `babel` with `babel-core`. `babel-runtime` is separate

**Comment by bucaran** [comment]
@thejameskyle I am using `babel-runtime` in the project already:

```
{ optional: ["runtime"] }
```

So, since that's already there, and everything works OK, I was wondering if adding `babel-core` would add any value?

**Comment by thejameskyle** [comment]
Go to the support chat, this is isn't the right place to be having this discussion.
